info:
  app:
    name: "Octo Events"
    description: "Octo Events is an application that listens to Github Events via webhooks and exposes an api for later use."
    version: 1.0.0
spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:octo-events
    username: sa
    password: senha
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
server:
  port: 9090

